language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: kkd8xvs5wuJylnA65SZEXsVHZdgU/G02eb1dkjVyZQ58k+F7HAoSqQYLa7q86vvkMqlYisnHrq5I6u3unOJYrmE9Bgu4mQV6UvPWgWMKY2XUQ3QUKf4WjSGFWYc7ARcEx8t4c5qC5bW/SV3lpSAOjqDRYcsQqa7JWkVfBr/cCqXmDQK6QjJHPLiu8DzFPpX39aD/fJF/4GsOaoSYvb/xOUFF3LcOJkfJDJ+xsDDJ1BhREjjvUjvgdrGMckrDwGVsO8/+hDuy7Xeyk95eQD6w8dH0BMLerxen1a8QAM4SOWq4W7x5V/hIOG68LMYMDpm2qcfRKoaDXaIAH1OVpImDuhBePoRxK+h2bGI436jcpWW02e0sBWOzEazoU0L+E/k9XcofuHT6hg1I8CYTFODFn9CY3u92PylMYG4fqxCcTeht+edxVdfevOL1aFDXa5/FYfYbLiDVDb7w2wubZH9APUTCivghgLYyy/56Kf1b/3D3dhRURCwwdPWHbH+WlTHoptp4epJ+zlqSwrR/579tERkvbP/AQcE4hMJx6uDUnH3E/Pkt8I/iKikZwvVW8jbmh0V5J/OJ49c4igtSThBnmu2X8eLDGKQG//fwNrXqvPSSGavuAXdOPY5UXYNKVdNHUqeTUN/qqi0rwHqrGLDu+pyBNy1QD94L74EXOJaPaDo=
  app: hellonode23
  on:
    repo: albosse/hellonode
