language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key: cqyEHBlSx3bgvMvrPXZHWRxqOc0J+FP9rl7DaVBwkWBVgnV97+Wo58jNQEYVhiwdS6u4GkSvIvMkCLGDcqlvjAL/MQbSIQizABHxZvVFX4hIfnVUO6Rqoq+Bguk/lsNlJMpQRkFBe48IJcNplsaC4NBdwLtR5MPN3v/mA+EkXjXbcEMnznyBBBGpYxz23nrZvfgSGmVdlBFCtl8NCmnKYIwHJa/f1u1MCC5/fO3fj9jI4dgy3vp2QYU9rEesEdAx3XkD99ksrNKF/m7UHF2aVEPvO4DU1QvjSYM7LEFPNAy+L08TlmiYHsRPSQBk0M+ynZq6qIphdJqVUcr9+If/F6FID2JsWYtMIU/aIK6a5QwwRvlUCXo6pROpvk9gUIPdpPc1IjfsppJs0KVeJGSDR3NOplVOKsWOlRGym6wYXBink4nmZpFY0lQIgCAxUpkN12JTKf7IBKdz8uLRQmlA5Iol3Aff6q8003uLwOCwO/Zdl3akRTaFRIW8jxcJq+1tJgFqpxh9zDdFLiCs8GlT/P5ga5qgTF91Um8m+0i6Pa4m36N/wWnp+HppW3Gj0rNeTSisX0hokFas/yzsq9ZVV38nWCnX2Z1J72MRX+KBp9GOarVy+Kgvr7tvHCWstVomzdVsSUQ841kdtWQhlaIinatP0fSA7xOJADSeiVPzAns=
  app: hellonode23
