language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: hellonode23
dd:
  secure: YIG4i5GCavyE7yANvK8aF7H9EuEEhBROvQ8JL7I5oP/SmDk3ax4twlYjbtxcZWFMe05WUkXLHkyRUMNlWRIBuzjJ/9/bYH8lhyKb/LkiKhEXIzPmbYMS8zKr1xJSYSYq1f6zKqp4/DvvZGMbk68w+bi2QVsfdHBkw5aLhOXSBxMplcTtNygj/3n6WcqpL05bfNCQM3OPSzemwGhP20VI6sFeCKIS2/alEp4+y7eEpXNVKuNP4qcjZ+obRdx+9MD9qgJ9sbCElRHXGu7VqccW4w0KhAhE3ZxEQ556FV6ld0M7qTW10ixoP7YzUI4EQCZHSFO1zPLkXmOhXLK1ERtHlw/4H0yG3qYG0zPAnTvI+Z3uAWb1Qexmlo36CqWkMImxcYIutRqxthsqeZ2UFOiTS2XKxDb36M48KT6kuxA5BMcj84I+CfwCBv1zbS8cPa2I0ruVijUKtZqsDAJrqiRve84IP5YmIrQxd6NH1Ac/znVD2k/8oVVAWxYLR7pR6ejClqqqeUhTEqvVpa5FiExCUS+ORyuOPc2OAbdgV+OaNpRx5NWqKODCDexbmIJfceluLQTlRbwW2yjzC2qQ3dD74bmSdrpCnvjJk+vr5kumMx2BEjfaEz81YPN6vCGpxUEuufRssRcedf9/TxT/MLsT2am4V/Dy16T+XiluV/5j7M8=
